Repository hbar-team/SPyCCI, pull requests merged in 2025-09, with the labels that each got.

#29 Refactored `System` class initialization and added alternative constructors
  docs/Guide/functions.md
  docs/Guide/run.md
  docs/Guide/setup.md
  docs/Guide/systems.md
  docs/Guide/tools.md
  docs/getting-started.md
  spycci/core/geometry.py
  spycci/engines/orca.py
  spycci/engines/xtb.py
  spycci/functions/pka.py
  spycci/systems.py
  spycci/tools/externalutilities.py
  spycci/wrappers/crest.py
  spycci/wrappers/packmol.py
  tests/functional/test_fukui.py
  tests/functional/test_pka.py
  tests/functional/test_potential.py
  tests/integration/test_crest_integration.py
  tests/integration/test_dftbplus_integration.py
  tests/integration/test_orca_integration.py
  tests/integration/test_packmol_integration.py
  tests/integration/test_xtb_integration.py
  tests/unit/test_externalutilities.py
  tests/unit/test_geometry.py
  tests/unit/test_spectroscopy.py
  tests/unit/test_systems.py
Labels: enhancement

#34 Remove hardcoded --mquick from crest calls
  pyproject.toml
  requirements.txt
  spycci/core/dependency_finder.py
  spycci/engines/dftbplus.py
  spycci/engines/orca.py
  spycci/engines/xtb.py
  spycci/tools/vmdtools.py
  spycci/wrappers/crest.py
  tests/functional/test_fukui.py
  tests/functional/test_pka.py
  tests/functional/test_potential.py
  tests/integration/test_crest_integration.py
  tests/integration/test_orca_integration.py
  tests/unit/test_dependency_finder.py
  tests/unit/test_dftbplus_unit.py
  tests/unit/test_orca_unit.py
  tests/unit/test_properties.py
  tests/unit/test_xtb_unit.py
  tox.ini
Labels: bug, enhancement

#36 Documentation update
  docs/API/core.md
  docs/Guide/run.md
  docs/Guide/setup.md
  docs/Guide/systems.md
  docs/contributor-guide.md
  docs/getting-started.md
  docs/intro.md
Labels: documentation
